Check scp draft Korean document
bosnet/papers pull request #10
Opened 2018-05-11 00:01 UTC by Charleslee522

1. reflect the review of the draft in Confluence
1. modify incorrect spacing
1. delete boscoin team's comment

2018-05-11 04:31 UTC, astonshnam commented
#6 과 conflict될 것 같은데요, #6 을 먼저 merge하고 승인해도 괜찮을런지요?

2018-05-14 02:10 UTC, soonkuk requested changes

2018-05-14 02:10 UTC, soonkuk commented on Stellar-Consensus-Protocol-IETF-Draft/Stellar-Consensus-Protocol-IETF-Draft.md
> +1. 어떤 설정과 실패 시나리오에서도, 두 노드의 safety를 보장하는 어떤 프로토콜 에서도, 어떤 두 개의 정상 노드도 모순되는 statements를 confirm 하지 않는다.
@Charleslee522 (즉, ill-behaved node에도 불구하고, 두 노드의 쿼럼 인터섹션은 safety를 만족한다.) 부분은 원래 draft에 포함되어 있는 부분인데요. 아마 저희가 추가한 해석으로 생각해서 삭제하신 것이 아닌가 생각되네요.

2018-05-23 01:32 UTC, Charleslee522 commented
> #6 과 conflict될 것 같은데요, #6 을 먼저 merge하고 승인해도 괜찮을런지요?
@astonshnam Why not?
@cmcm2222 Please review #6 first.

2018-05-23 02:09 UTC, astonshnam commented
@Charleslee522 I merged #6 . So there is conflicting file.

2018-05-23 03:58 UTC, Charleslee522 commented
@soonkuk Please review again.
@astonshnam @cmcm2222 Please check this pr.

2018-05-23 04:37 UTC, johndoe0x approved these changes
LGTM

2018-05-23 09:36 UTC, soonkuk approved these changes

2018-05-23 10:16 UTC, sconeman approved these changes
LGTM!

2018-05-24 01:39 UTC, merged